### ISSUE TITLE
Introduction

### ISSUE THREAD

**Issue by venam** [thelostt/ricing#13]
Hello thelostt,
Wouldn't the book be better if it started with an introductory chapter0 instead of chapter1 that jumps directly in the core of the subject.

What I'm thinking of is simply copying/linking the content of the README.md to chapter0.md.

What's your take on that?

**Comment by feroldi** [comment]
We can do that when there are more items to the book.

**Comment by feroldi** [comment]
Any updates on this?

**Comment by venam** [comment]
I haven't touched this repo in months.
I thought the project had been left or was stagnating.

**Comment by feroldi** [comment]
You're a collaborator, do whatever you think is right :)
