### ISSUE TITLE
Code guideline

### ISSUE THREAD

**Issue by randomn4me** [thelostt/ricing#18]
Is there any coding guideline when contributing, like one sentence per line or textwidth of 80?

**Comment by feroldi** [comment]
It's in the CONTRIB.md file, though it's not strict. [This](https://github.com/thelostt/ricing/blob/master/CONTRIB.md#hows-the-itemschapters-skeleton) is the minimum required.

**Comment by randomn4me** [comment]
Okay, thanks.
