### ISSUE TITLE
Suggestion for linking - my repo

### ISSUE THREAD

**Issue by SuperCuber** [thelostt/ricing#2]
In my dotfiles repo I have an install script - maybe you could use it as an example for your chapter 1
https://github.com/SuperCuber/dotfiles/blob/master/install

**Comment by feroldi** [comment]
I've already written about managing dotfiles like that (not yet committed). I don't want the reader to copy-paste working examples from the book, but rather understand the steps torward building his/her own environment. Sure, I could break your script down into small parts and just explain them, but you're using some stuff that aren't POSIX compliant, and the reader would, again, just copy those stuff and "get work done quick."

But I appreciate and welcome any help from anyone, so thanks.

**Comment by feroldi** [comment]
I'm reopening this issue in case you want to say something.

**Comment by SuperCuber** [comment]
Don't worry about it :D
