### ISSUE TITLE
Any plans on a LaTeX version alongside Markdown?

### ISSUE THREAD

**Issue by ghost** [thelostt/ricing#23]
I'm sure many readers as myself would love to be able to print out a nice looking PDF but I do understand that Markdown is the best language to use for Reddit and Github in terms of formatting friendliess. This is probably too far-future thinking but `pandoc` sounds like a program of interest for you; it takes one textual input and produces many different outputs i.e. Markdown+LaTeX, so you need not worry about duplication of effort or doing extra work (besides reading the manpages of course :)

**Comment by feroldi** [comment]
Yes, I made it fairly straightforward to generate other formats from the Markdown files: https://github.com/feroldi/ricing#more-file-formats

Now, if the question is: "should we provide a **LaTeX** version of the book in the repository?" Then I'm not sure. Maybe do it on releases?

Regardless, I'm not actively working on this project, as you can tell by the most recent commit's date. You're welcome to fork it and PR anything though.

**Comment by ghost** [comment]
My bad didn't read. Yeah I agree it should be done on major milestone releases, the users who want the latest nightly can just compile the build themselves.
